// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "ap-northeast-1",
  "aws_cognito_identity_pool_id": "ap-northeast-1:7884b1c9-4813-4be4-82eb-a1c7e23a6ee1",
  "aws_cognito_region": "ap-northeast-1",
  "aws_user_pools_id": "ap-northeast-1_AzXeoJNuF",
  "aws_user_pools_web_client_id": "4iopmdreohc2jbauaoeokuhbr4",
  "oauth": {}
};


export default awsmobile;
